### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by angelozerr** [katspaugh/tj-mode#7]
@katspaugh I have started to integrate your higlight tern plugin inside Eclipse but I had several problems and I had to modify your code in order to it works for Eclipse. 

I have 2 choices : 
- use your tern plugin if you accept my changes.
- create my own tern plugin (very shame -())

The first thing which is very important is the performance (with big files). With your tern plugin I have a big problems with performance because you need to post tern file before calling your query "higlight". This post of tern file execute the analyse of the tern file each time you are typing, which is a problem for performance. 

Indeed, with you tern plugin, you must post tern file and call after your "higlight" tern query which loops for each posted tern files (why a loop?, highlight is just for a given file, no?).

My change is that I set the text content in the query to avoid posting tern file:
- pros : provide a very good performance
- cons: you loose information of the type like your Error/Warning message (with Identifier which uses expressionType).

But IMHO, Highlight must be just higlight tokens and not manage validation. Validation must be done with other linter like tern-lint or https://github.com/marijnh/blint which is based on acorn too.

If you are OK with my suggestion (not to use tern file, but just set the text file content in the query), I will create a PR. 

I hope you will be OK, because I have improved your higlight to higlight even if js code is not valid like : 

``` javascript
var 
var a = 10 // here highlight doesn't work because teh first var breaks acorn parser.
```

I would like to provide ES6 higlight features. Hope we will able to work together.

**Comment by katspaugh** [comment]
I'm fine with moving out undefined variables linting out of the plugin. Simple syntax checks should still be there, I think.

> I have improved your higlight to higlight even if js code is not valid like :

I actually think this is an anti-feature :) If the syntax is invalid why should it be highlighted?

Anyway, I would be happy to review your PR. Thanks!

**Comment by angelozerr** [comment]
>  Simple syntax checks should still be there, I think.

Cool!

> I actually think this is an anti-feature :) If the syntax is invalid why should it be highlighted?

All editors works like this. See github : 

``` javascript
var 
var a = 10 // here highlight doesn't work because teh first var breaks acorn parser.
```

The `var a` is hihlighted here. It's an other topic. I'm preparing a PR.

**Comment by angelozerr** [comment]
Done https://github.com/katspaugh/tj-mode/pull/8

**Comment by katspaugh** [comment]
I've pulled your changes in #9.

**Comment by angelozerr** [comment]
Thanks! But is it working with https://github.com/katspaugh/tj-mode/blob/master/tj-mode.el ? You need changes something since text content comes from query.text, no?

**Comment by katspaugh** [comment]
The Emacs package is up-to-date now: https://github.com/katspaugh/tj-mode/commit/d23c297bc239a15d2f8025172901263fb93b5e82
